notears:
  # Best NOTEARS config after hp tuning
  lambda1:
    raw_w_0.5_2.0_n_1.0_1.0: 0.00
    final_w_0.5_2.0_n_1.0_1.0: 0.15
    alternate_w_0.5_2.0_n_1.0_1.0: 0.15
    raw_w_1.3_3.0_n_1.0_1.0: 0.05
    final_w_1.3_3.0_n_1.0_1.0: 0.25
    alternate_w_1.3_3.0_n_1.0_1.0: 0.20
    raw_w_0.3_0.8_n_1.0_1.0: 0.05
    final_w_0.3_0.8_n_1.0_1.0: 0.15
    alternate_w_0.3_0.8_n_1.0_1.0: 0.15

  w_threshold:
    raw_w_0.5_2.0_n_1.0_1.0: 0.3
    final_w_0.5_2.0_n_1.0_1.0: 0.2
    alternate_w_0.5_2.0_n_1.0_1.0: 0.1
    raw_w_1.3_3.0_n_1.0_1.0: 0.3
    final_w_1.3_3.0_n_1.0_1.0: 0.1
    alternate_w_1.3_3.0_n_1.0_1.0: 0.1
    raw_w_0.3_0.8_n_1.0_1.0: 0.2
    final_w_0.3_0.8_n_1.0_1.0: 0.1
    alternate_w_0.3_0.8_n_1.0_1.0: 0.1

  __run__:
    n_cpus: 1
    n_gpus: 0
    length: short
    grouped: True

golem_ev:
  # Best GOLEM-EV config after hp tuning
  lambda_1:
    raw_w_0.5_2.0_n_1.0_1.0: 0.002
    final_w_0.5_2.0_n_1.0_1.0: 0.020
    alternate_w_0.5_2.0_n_1.0_1.0: 0.020
    raw_w_1.3_3.0_n_1.0_1.0: 0.002
    final_w_1.3_3.0_n_1.0_1.0: 0.020
    alternate_w_1.3_3.0_n_1.0_1.0: 0.020
    raw_w_0.3_0.8_n_1.0_1.0: 0.020
    final_w_0.3_0.8_n_1.0_1.0: 0.020
    alternate_w_0.3_0.8_n_1.0_1.0: 0.020

  lambda_2:
    raw_w_0.5_2.0_n_1.0_1.0: 5.00
    final_w_0.5_2.0_n_1.0_1.0: 8.00
    alternate_w_0.5_2.0_n_1.0_1.0: 2.00
    raw_w_1.3_3.0_n_1.0_1.0: 5.00
    final_w_1.3_3.0_n_1.0_1.0: 8.00
    alternate_w_1.3_3.0_n_1.0_1.0: 5.00
    raw_w_0.3_0.8_n_1.0_1.0: 2.00
    final_w_0.3_0.8_n_1.0_1.0: 5.00
    alternate_w_0.3_0.8_n_1.0_1.0: 5.00

  w_threshold:
    raw_w_0.5_2.0_n_1.0_1.0: 0.3
    final_w_0.5_2.0_n_1.0_1.0: 0.1
    alternate_w_0.5_2.0_n_1.0_1.0: 0.1
    raw_w_1.3_3.0_n_1.0_1.0: 0.3
    final_w_1.3_3.0_n_1.0_1.0: 0.1
    alternate_w_1.3_3.0_n_1.0_1.0: 0.1
    raw_w_0.3_0.8_n_1.0_1.0: 0.1
    final_w_0.3_0.8_n_1.0_1.0: 0.1
    alternate_w_0.3_0.8_n_1.0_1.0: 0.1

  equal_variances: True
  learning_rate: 0.001

  __run__:
    n_cpus: 1
    n_gpus: 0
    grouped_length: short
    grouped: 6

golem_nv:
  # Best GOLEM-NV config after hp tuning
  lambda_1:
    raw_w_0.5_2.0_n_1.0_1.0: 0.0002
    final_w_0.5_2.0_n_1.0_1.0: 0.0200
    alternate_w_0.5_2.0_n_1.0_1.0: 0.0200
    raw_w_1.3_3.0_n_1.0_1.0: 0.0002
    final_w_1.3_3.0_n_1.0_1.0: 0.0002
    alternate_w_1.3_3.0_n_1.0_1.0: 0.0200
    raw_w_0.3_0.8_n_1.0_1.0: 0.0020
    final_w_0.3_0.8_n_1.0_1.0: 0.0200
    alternate_w_0.3_0.8_n_1.0_1.0: 0.0200

  lambda_2:
    raw_w_0.5_2.0_n_1.0_1.0: 2.00
    final_w_0.5_2.0_n_1.0_1.0: 2.00
    alternate_w_0.5_2.0_n_1.0_1.0: 2.00
    raw_w_1.3_3.0_n_1.0_1.0: 2.00
    final_w_1.3_3.0_n_1.0_1.0: 5.00
    alternate_w_1.3_3.0_n_1.0_1.0: 2.00
    raw_w_0.3_0.8_n_1.0_1.0: 5.00
    final_w_0.3_0.8_n_1.0_1.0: 2.00
    alternate_w_0.3_0.8_n_1.0_1.0: 2.00

  w_threshold:
    raw_w_0.5_2.0_n_1.0_1.0: 0.2
    final_w_0.5_2.0_n_1.0_1.0: 0.1
    alternate_w_0.5_2.0_n_1.0_1.0: 0.2
    raw_w_1.3_3.0_n_1.0_1.0: 0.1
    final_w_1.3_3.0_n_1.0_1.0: 0.1
    alternate_w_1.3_3.0_n_1.0_1.0: 0.2
    raw_w_0.3_0.8_n_1.0_1.0: 0.2
    final_w_0.3_0.8_n_1.0_1.0: 0.2
    alternate_w_0.3_0.8_n_1.0_1.0: 0.1

  equal_variances: False
  learning_rate: 0.001

  __run__:
    n_cpus: 1
    n_gpus: 0
    grouped_length: short
    grouped: 6

pc:
  # Best PC config after hp tuning
  ci_alpha:
    raw_w_0.5_2.0_n_1.0_1.0: 0.01
    final_w_0.5_2.0_n_1.0_1.0: 0.01
    alternate_w_0.5_2.0_n_1.0_1.0: 0.01
    raw_w_1.3_3.0_n_1.0_1.0: 0.01
    final_w_1.3_3.0_n_1.0_1.0: 0.01
    alternate_w_1.3_3.0_n_1.0_1.0: 0.01
    raw_w_0.3_0.8_n_1.0_1.0: 0.01
    final_w_0.3_0.8_n_1.0_1.0: 0.01
    alternate_w_0.3_0.8_n_1.0_1.0: 0.01
  ci_test:
    raw_w_0.5_2.0_n_1.0_1.0: gaussian
    final_w_0.5_2.0_n_1.0_1.0: gaussian
    alternate_w_0.5_2.0_n_1.0_1.0: gaussian
    raw_w_1.3_3.0_n_1.0_1.0: gaussian
    final_w_1.3_3.0_n_1.0_1.0: gaussian
    alternate_w_1.3_3.0_n_1.0_1.0: gaussian
    raw_w_0.3_0.8_n_1.0_1.0: gaussian
    final_w_0.3_0.8_n_1.0_1.0: gaussian
    alternate_w_0.3_0.8_n_1.0_1.0: gaussian

  __run__:
    n_cpus: 1
    n_gpus: 0
    length: short
    grouped: True

ges:
  __run__:
    n_cpus: 1
    n_gpus: 0
    length: short
    grouped: True

varsortregress:
  __run__:
    n_cpus: 1
    n_gpus: 0
    length: short
    grouped: True

r2sortregress:
  __run__:
    n_cpus: 1
    n_gpus: 0
    length: short
    grouped: True

randomsortregress:
  __run__:
    n_cpus: 1
    n_gpus: 0
    length: short
    grouped: True

avici:
  model: linear
  prob_threshold: 0.5

  __run__:
    n_cpus: 1
    n_gpus: 0
    mem: 12000
    length: short
    grouped: True
#
lingam:
  __run__:
    n_cpus: 1
    n_gpus: 0
    length: short
    grouped: True

#score:
#  __run__:
#    n_cpus: 1
#    n_gpus: 0
#    grouped_length: short
#    grouped: 6

cam:
  alpha:
    raw_w_0.5_2.0_n_1.0_1.0: 0.10
    final_w_0.5_2.0_n_1.0_1.0: 0.10
    alternate_w_0.5_2.0_n_1.0_1.0: 0.10
    raw_w_1.3_3.0_n_1.0_1.0: 0.05
    final_w_1.3_3.0_n_1.0_1.0: 0.05
    alternate_w_1.3_3.0_n_1.0_1.0: 0.05
    raw_w_0.3_0.8_n_1.0_1.0: 0.05
    final_w_0.3_0.8_n_1.0_1.0: 0.05
    alternate_w_0.3_0.8_n_1.0_1.0: 0.05

  nsplines:
    raw_w_0.5_2.0_n_1.0_1.0: 10
    final_w_0.5_2.0_n_1.0_1.0: 10
    alternate_w_0.5_2.0_n_1.0_1.0: 5
    raw_w_1.3_3.0_n_1.0_1.0: 10
    final_w_1.3_3.0_n_1.0_1.0: 10
    alternate_w_1.3_3.0_n_1.0_1.0: 5
    raw_w_0.3_0.8_n_1.0_1.0: 5
    final_w_0.3_0.8_n_1.0_1.0: 5
    alternate_w_0.3_0.8_n_1.0_1.0: 5

  degsplines:
    raw_w_0.5_2.0_n_1.0_1.0: 3
    final_w_0.5_2.0_n_1.0_1.0: 2
    alternate_w_0.5_2.0_n_1.0_1.0: 2
    raw_w_1.3_3.0_n_1.0_1.0: 2
    final_w_1.3_3.0_n_1.0_1.0: 3
    alternate_w_1.3_3.0_n_1.0_1.0: 2
    raw_w_0.3_0.8_n_1.0_1.0: 3
    final_w_0.3_0.8_n_1.0_1.0: 2
    alternate_w_0.3_0.8_n_1.0_1.0: 3

  __run__:
    n_cpus: 1
    n_gpus: 0
    grouped_length: short
    grouped: 6
